FROM projectorimages/projector-clion:2021.1.1

USER root

RUN echo \
"deb http://mirrors.aliyun.com/debian/ buster main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ buster main non-free contrib\n\
deb http://mirrors.aliyun.com/debian-security buster/updates main\n\
deb-src http://mirrors.aliyun.com/debian-security buster/updates main\n\
deb http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib\n\
deb http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib" \
    > /etc/apt/sources.list

RUN apt-get update && apt-get install -qq -y --fix-missing --no-install-recommends \
    curl \
    wget \
    unzip \
    && apt-get autoremove -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /usr/share/locale/* \
    && rm -rf /var/cache/debconf/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc/*

# install rust
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static \
    RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup \
    RUST_VERSION=1.52.0

RUN set -eux; \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) rustArch='x86_64-unknown-linux-gnu'; rustupSha256='fb3a7425e3f10d51f0480ac3cdb3e725977955b2ba21c9bdac35309563b115e8' ;; \
        armhf) rustArch='armv7-unknown-linux-gnueabihf'; rustupSha256='f263e170da938888601a8e0bc822f8b40664ab067b390cf6c4fdb1d7c2d844e7' ;; \
        arm64) rustArch='aarch64-unknown-linux-gnu'; rustupSha256='de1dddd8213644cba48803118c7c16387838b4d53b901059e01729387679dd2a' ;; \
        i386) rustArch='i686-unknown-linux-gnu'; rustupSha256='66c03055119cecdfc20828c95429212ae5051372513f148342758bb5d0130997' ;; \
        *) echo >&2 "unsupported architecture: ${dpkgArch}"; exit 1 ;; \
    esac; \
    url="https://static.rust-lang.org/rustup/archive/1.24.1/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch}; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version; \
    rustup component add rust-src

RUN chmod 777 /home/$PROJECTOR_USER_NAME

USER $PROJECTOR_USER_NAME

ARG RUST_PLUGIN_URL="https://plugins.jetbrains.com/files/8182/122019/intellij-rust-0.4.148.3911-211.zip"
ARG TOML_PLUGIN_URL="https://plugins.jetbrains.com/files/8195/122016/intellij-toml-0.2.148.3911-211.zip"
RUN curl -fSL ${RUST_PLUGIN_URL} -o /tmp/rust.zip \
    && curl -fSL ${TOML_PLUGIN_URL} -o /tmp/tmol.zip \
    && mkdir -p /home/$PROJECTOR_USER_NAME/.local/share/JetBrains/CLion2021.1 \
    && unzip /tmp/rust.zip -d /home/$PROJECTOR_USER_NAME/.local/share/JetBrains/CLion2021.1 \
    && unzip /tmp/tmol.zip -d /home/$PROJECTOR_USER_NAME/.local/share/JetBrains/CLion2021.1 \
    && rm /tmp/rust.zip \
    && rm /tmp/tmol.zip